spring:
  cloud:
    gateway:
      routes:
        - id: throttle_route
          uri: http://localhost:8080
          predicates:
            - Path=/api/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20

spring:
  redis:
    host: localhost
    port: 6379